### ISSUE TITLE
Cannot find module 'availability-monitor' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by 6xtvo** [pbombnz/availability-monitor#2]
I tried installing this with yarn (v1.22.18) in my TypeScript project, but when I try importing the module I get an error saying the module can't be found.

**Comment by pbombnz** [comment]
Hi, Sorry for the long wait. Should be fixed with 'v1.1.4' now. Will leave the issue open for a little bit if would like to place on-going feedback.
